using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Connectome.Twitter.API
{
    class Program
    {
        static void Main(string[] args)
        {
            TwitterAPI api = TwitterAPI.Instance;
            api.initializeAuthentication();
            Console.WriteLine("Please enter this URL in your browser: " + api.getAuthorizationURL());
            Console.WriteLine("Please enter the PIN code generated by your browser: ");
            String pinCode = Console.ReadLine();
            api.enterPINCode(pinCode);
            var timelineTweets = api.getUserHomeTimeLine();
        }
    }
}
